export const devsApproved: string[] = [
  "Larissa Paim Ribeiro",
  "Ingrid Couto Rosin",
  "Bruna Ribeiro",
  "Felipe Mamede",
  "Renato de Souza Alves",
  "Cesar Batista Rodrigues Machado",
  "Victória Dalceno José Pedro",
  "Charles Carris Omena Mota",
  "Lucas Vinicius Pessoa de França",
  "Nadir Grieger",
  "Grazi Nascimento",
  "Ludmila Magalhães",
  "Carlos Henrique Palmeira De Matos",
  "Alexsandro da silva costa",
  "Dangels Maia Chaves",
  "Cassia Santos",
  "Carlos Verissimo Barbosa Caxias",
  "Ian Da Silva Santana",
  "Dandara Fonseca da Silva",
  "Elis Grace Batista da Silva Lages",
  "Lázaro josé de lima silva",
  "Isabella Cristina Rodrigues Ramos",
  "Cristian Calegari",
  "Rafaella Vitória Almeida Marcelino",
  "Suian Couto Melro",
  "Rafaela Bruna Miranda ",
  "Fernanda Barreiros Nardoni",
  "Izabela Mateus ",
  "Izadora Silva Oliveira",
  "Kainê Tomaschitz Marghotti",
  "Daniele Marques Silva",
  "Fabio dos Santos Brito",
  "Fernando Herstler Albernaz",
  "Renan dos Santos Pinto",
  "Aida de Figueiredo Tavares",
  "Mariana Caetano Pereira",
  "Tamires Cristina da Silva Vicente",
  "Camila de Paula Bentes Pessôa",
  "Ramon Xavier Moreira",
  "Beatriz Massola",
  "Marco Tulio Daher e Silva Padua",
  "Everson Messias da Silva",
  "Felipe Tomatis Peres",
  "Ana Paula da Silva Lima",
  "Luan José De Aquino Cahú Siqueira ",
  "Kevin Braga de Alcantara",
  "Pedro Ikaro Sandes Alves",
  "Amanda Oliveira Mota da Silva",
  "Marcos da Silva de Oliveira",
  "Luiz Henrique Garcia Marques",
  "Sergio Madureira Gomes Junior",
  "Leandro Vieira de Almeida",
  "Cid Damasceno Jales",
  "João Vitor Alves da Silva",
  "Ranniery Almeida Marques",
  "Alanna Maria Machado Alves Paiva",
  "Tomás Rajão de Faria",
  "Eloy Picanço Farias Neto",
  "Jônatas Mendonça de Vasconcelos Brito",
  "Hugo de Sousa Bello",
];

export const designersApproved: string[] = [
  "Camila Carvalho Cardoso de Santana",
  "Camila Maria Dias de Araujo Barros",
  "Lara Cardoso Figueirêdo",
  "Daniela Luiza Duwe Heiderscheidt",
  "Iris F. B. Paulo",
  "Rafael Amaral Esteves Dos Santos",
  "Juliane Pires",
  "Maria Libiane de Resende Tomé",
  "Leonardo Nogueira Bastos ",
  "Lucas Santana de Oliveira",
  "Isabela Menezes Baur Gomes",
  "Samylla Suzane Leão Wanderley",
  "Pedro Antônio de Paula Freitas",
  "Fabiana Cruz de Araújo",
  "William Freitas de Souza",
  "Patricia Marinho",
  "Gabriela Bernardoni de Vasconcelos",
  "Andreia Pereira de Oliveira",
  "Natália de Souza Santiago",
  "Fabricio da Silva",
  "Sara Pereira da Silva",
  "Vitória Silva Avandaño Paiva",
  "Mateus Francisco da Silva",
  "Pedro Júlio Soares Santos",
  "Adriano Grego Neves",
  "Jade Oliveira",
  "Pablo Batista Martins de Assis Braz ",
  "Filipe Soares Dantas",
  "Alexandra Cristina Rodrigues Ferreira",
  "Andréa Jainy Gomes de Souza",
  "Eduardo Borges Guioti Fontana ",
  "Lorrana Keller Monteiro Siqueira",
  "Lucas Bail",
  "Veronica Helena R P M  Carneiro",
  "Aline Fank Maciel Viana",
  "Bruno Andrade Castilho",
  "Adriano Carvalho da Silva",
  "Wanessa Lanne de Araújo Batista",
  "Thayna Cristina da Silva ",
  "Marcelle Cristina da Silva Souza",
  "Caroline de Brito Schicowski",
  "Julia Nascimento Barata Godinho",
  "Willian Pereira da Silva",
  "Roziana Rodrigues",
  "Caroline Soares",
  "Izabella Xavier Pereira",
  "Tamara dos Santos Costa",
  "Anna Cecília do Nascimento Pereira Maciel",
  "Grace Kelly do Rocio Selucsnak",
  "Anna Clara Lima De Almeida",
];

interface IStudentsApproved<T> {
  [key: string]: T;
}

export const studentsApproved: IStudentsApproved<string[]> = {
  dev: devsApproved,
  design: designersApproved,
};

export const getApprovedList = (list: string) => studentsApproved[list];
