export const devsApproved: string[] = [
  "Aida Figueredo",
  "Amanda Silva",
  "Camila Pessoa",
  "Carlos Henrique",
  "Cesar Machado",
  "Charles Carris",
  "Cid Damasceno",
  "Cristian Calegari",
  "Dandara Silva",
  "Daniele Marques",
  "Elis Lages",
  "Eloy Pacheco",
  "Fabio dos Santos Brito",
  "Felipe Tomatis",
  "Fernanda Nardoni",
  "Izadora Oliveira",
  "Kevin Alcantara",
  "Larissa Paim",
  "Ludmila Magalhães",
  "Marcos da Silva de Oliveira",
  "Mariana Caetano",
  "Ana Paula da Silva Lima",
  "Pedro Sandes",
  "Rafaela Bruna Miranda ",
  "Rafaella Vitória Almeida Marcelino",
  "Ramom Xavier",
  "Renato Alves",
  "Sergio junior",
  "Suian Couto",
  "Tamires Cristina",
];

export const designersApproved: string[] = [
  "Adriano Carvalho",
  "Adriano Grego",
  "Alexandra Rodrigues",
  "Andreia Oliveira",
  "Anna Cecilia",
  "Anna Clara Lima",
  "Camila Araujo",
  "Eduardo Borges",
  "Fabricio Silva",
  "Grace Kelly",
  "Iris Beringher",
  "Jade Oliveira",
  "Julia Goldinho",
  "Libiane Tomé",
  "Lorrana Keller",
  "Lucas Bail",
  "Lucas Santana",
  "Marcelle Souza",
  "Natália de Souza Santiago",
  "Pablo Batista",
  "Patricia Marinho",
  "Pedro Julio",
  "Roziana Rodrigues",
  "Samylla Suzane",
  "Sara Silva",
  "Tamara Costa",
  "Thayna Cristina da Silva",
  "Vitoria Avendano",
  "Wanessa Lanne",
  "Willian Pereira",
];

interface IStudentsApproved<T> {
  [key: string]: T;
}

export const studentsApproved: IStudentsApproved<string[]> = {
  dev: devsApproved,
  design: designersApproved,
};

export const getApprovedList = (list: string) => studentsApproved[list];
