name: CD
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install yarn
        run: npm install -g yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build project
        run: yarn build:exp
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: sa-east-1
      - name: Deploy app
        run: aws s3 sync ./out s3://estartandodevs-site --acl public-read
