name: Notify Deploy DEV
on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: send message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "GitHub Bot"
          message: "A new version has been published for ${{ github.repository }} by ${{ github.actor }}."
